export const adminUser = [
    {
      group: "Dashboard",
      id: "1",
      image: "home1",
      name: "Dasboard",
      permissions: {
        borrar: true,
        create: true,
        edit: true,
        view: true,
      },
      url: "/revenue/growth/web/home",
    },
    {
      group: "Campaigns",
      id: "2",
      image: "home1",
      name: "Campañas",
      permissions: {
        view: true,
        create: true,
        edit: true,
        borrar: true,
      },
      url: "/revenue/growth/web/campaing",
    },
    {
      group: "Touches",
      id: "3",
      image: "home1",
      name: "Toques",
      permissions: {
        view: true,
        create: true,
        edit: true,
        borrar: true,
      },
      url: "/revenue/growth/web/touches",
    },
    {
      group: "CreateCampaing",
      id: "4",
      image: "home1",
      name: "Crear Campaña",
      permissions: {
        view: true,
        create: true,
        edit: true,
        borrar: true,
      },
      url: "/revenue/desafios/dashboard",
    },
    {
      group: "Drafts",
      id: "5",
      image: "home1",
      name: "Borradores",
      permissions: {
        view: true,
        create: true,
        edit: true,
        borrar: true,
      },
      url: "/revenue/desafios/dashboard",
    },
    {
      group: "Authorizer",
      id: "8",
      image: "home5",
      name: "Documentos legales",
      permissions: { view: true, create: true, edit: true, borrar: true },
      url: "/revenue/terminosycondiciones/dashboard",
    },
    {
      group: "Administrator",
      id: "9",
      image: "home3",
      name: "Catálogos",
      permissions: {
        view: true,
        create: true,
        edit: true,
        borrar: true,
      },
      url: "/revenue/catalogos/dashboard",
    },
    {
      group: "Banners",
      id: "9",
      image: "home3",
      name: "Banners",
      permissions: {
        view: true,
        create: true,
        edit: true,
        borrar: true,
      },
      url: "/revenue/catalogos/dashboard",
    },
    {
      group: "Panel de Control",
      id: "6",
      image: "home1",
      name: "Administracion de catálogos",
      permissions: {
        view: true,
        create: true,
        edit: true,
        borrar: true,
      },
      url: "/revenue/panel/1",
    },
    {
      group: "Panel de Control",
      id: "7",
      image: "home1",
      name: "Tiempo de aprobacion de toques",
      permissions: {
        view: true,
        create: true,
        edit: true,
        borrar: true,
      },
      url: "/revenue/panel/2",
    },
    {
      group: "AdminFiles",
      id: "8",
      image: "home1",
      name: "Administrador de Imagenes",
      permissions: {
        view: true,
        create: true,
        edit: true,
        borrar: true,
      },
      url: "/revenue/growth/web/files",
    },
  ];
  